publicHost: https://localhost:8080
keyPath: /etc/ghost-idp/certs/tls.key

attestation:
  enabled: false
  requiredFor:
    - mobile
  provider: noop

token:
  ttl: 2h
  tokenRequestDelay:
    minMS: 500
    maxMS: 1500
  config:
    dev:
      ttl: 3h
      audience:
        - env-dev
        - env-qa
    prod:
      ttl: 2h
      audience:
        - env-prod

clients:
  web:
    - name: kompass-web-dev
      config: dev
      allowedOrigins:
        - "*"

  mobile:
    - name: kompass-mobile-dev
      config: dev
    - name: kompass-mobile-prod
      config: prod
